language: python
sudo: false
cache:
  - ccache
  - pip
addons:
  apt:
    packages:
      - libatlas-dev
      - libblas-dev
      - liblapack-dev
      - python${TRAVIS_PYTHON_VERSION}-dev
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - python setup.py develop
script:
  - python setup.py test
